apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-ingress
  labels:
    app: observability
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "observability-ip"
    networking.gke.io/managed-certificates: "observability-ssl-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: observability.yourdomain.com # Replace with your domain
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
              name: observability-a-service
              port:
                number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: observability-ssl-cert
spec:
  domains:
    - observability.yourdomain.com # Replace with your domain
