---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: observability
  annotations:
    iam.gke.io/gcp-service-account: gke-observability-collector@saral-458210.iam.gserviceaccount.com